spring:
  profiles:
    active:${ENV:test}
  data:
    mongodb:
      host: localhost
      port: 27017

mongock:
  migration-scan-package:
    - com.cards.apirest.migrations
#  trackIgnored: true
#  transactionEnabled: true
#  runner-type: InitializingBean
#  mongo-db:
#    read-concern: local


    #spring.data.mongodb.database=java-to-dev-api
    #spring.data.mongodb.pass=admin
    #spring.data.mongodb.user=admin

